name: Google Form Issue

on:
  repository_dispatch:
    types: [google_form]

permissions:
  issues: write
  contents: read
  models: read

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Open issue with form response
        id: create
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const { createIssueFromForm } = require('./scripts/google_form_issue.js');
            await createIssueFromForm({ github, context, core, fetch });
      - name: Summarize LLM call
        if: always()
        run: |
          {
            echo "LLM API called: ${{ steps.create.outputs.llm_called }}";
            if [ -n "${{ steps.create.outputs.llm_error }}" ]; then
              echo "Error: ${{ steps.create.outputs.llm_error }}";
            fi
            if [ -n "${{ steps.create.outputs.llm_toxic }}" ]; then
              echo "Toxic verdict: ${{ steps.create.outputs.llm_toxic }}";
            fi
          } >> "$GITHUB_STEP_SUMMARY"
