

name: Google Form Issue

on:
  repository_dispatch:
    types: [google_form]

permissions:
  issues: write
  contents: read
  models: read

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Open issue with form response
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const { createIssueFromForm } = require('./scripts/google_form_issue.js');
            await createIssueFromForm({ github, context, core, fetch });
